openapi: 3.0.3
info:
  title: Argent Bank API documentation
  description: Contains all proposed API endpoints for transactions
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
  - url: localhost:3001/api/v1
paths:
  /user/transactions:
    get:
      tags:
        - Transactions Module
      summary: Retrieve transactions by page and time period
      description: Retrieve transactions by page and time period
      parameters:
        - in: query
          name: pageNumber
          type: integer
          example: 1
          required: true
          description: Number of page to collect the transactions.
        - in: query
          name: startDate
          type: string
          example: '2022-09-04'
          description: Start date to collect the transactions
        - in: query
          name: endDate
          example: '2022-10-04'
          type: string
          description: End date to collect the transactions
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 100000
                    date:
                      type: string
                      example: '2022-09-01'
                    description:
                      type: string
                      example: Golden Sun Bakery
                    amount:
                      type: number
                      format: float
                      example: 5
                    currency:
                      type: string
                      example: EUR
                    balance:
                      type: number
                      format: float
                      example: 2082.79
            application/xml:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 100000
                    date:
                      type: string
                      example: '2022-09-01'
                    description:
                      type: string
                      example: Golden Sun Bakery
                    amount:
                      type: number
                      format: float
                      example: 5
                    currency:
                      type: string
                      example: EUR
                    balance:
                      type: number
                      format: float
                      example: 2082.79
        '400':
          description: Invalid data supplied
        '404':
          description: Transactions not found
        '405':
          description: Validation exception
      security:
        - Bearer: []
    post:
      tags:
        - Transactions Module
      summary: Create a new transaction
      description: Create a new transaction
      requestBody:
        description: New transaction
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: '2022-09-01'
                description:
                  type: string
                  example: Golden Sun Bakery
                amount:
                  type: number
                  format: float
                  example: 5
                currency:
                  type: string
                  example: EUR
          application/xml:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: '2022-09-01'
                description:
                  type: string
                  example: Golden Sun Bakery
                amount:
                  type: number
                  format: float
                  example: 5
                currency:
                  type: string
                  example: EUR
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: '2022-09-01'
                description:
                  type: string
                  example: Golden Sun Bakery
                amount:
                  type: number
                  format: float
                  example: 5
                currency:
                  type: string
                  example: EUR
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  date:
                    type: string
                    example: '2022-09-01'
                  description:
                    type: string
                    example: Golden Sun Bakery
                  amount:
                    type: number
                    format: float
                    example: 5
                  currency:
                    type: string
                    example: EUR
                  balance:
                    type: number
                    format: float
                    example: 2082.79
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  date:
                    type: string
                    example: '2022-09-01'
                  description:
                    type: string
                    example: Golden Sun Bakery
                  amount:
                    type: number
                    format: float
                    example: 5
                  currency:
                    type: string
                    example: EUR
                  balance:
                    type: number
                    format: float
                    example: 2082.79
        '405':
          description: Invalid input
      security:
        - Bearer: []
  /user/transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Retrieve details of a transaction
      description: Retrieve details of a transaction
      parameters:
        - in: path
          name: transactionId
          example: 1
          required: true
          description: Numeric id of the transaction
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  transactionId:
                    type: integer
                    format: int64
                    example: 1000
                  createdAt:
                    type: string
                    example: '2022-09-04'
                  updatedAt:
                    type: string
                    example: '2022-09-04'
                  type:
                    type: string
                    example: electronic
                  category:
                    type: string
                    example: food
                  notes:
                    type: string
                    example: notes
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  transactionId:
                    type: integer
                    format: int64
                    example: 1000
                  createdAt:
                    type: string
                    example: '2022-09-04'
                  updatedAt:
                    type: string
                    example: '2022-09-04'
                  type:
                    type: string
                    example: electronic
                  category:
                    type: string
                    example: food
                  notes:
                    type: string
                    example: notes
        '405':
          description: Invalid input
      security:
        - Bearer: []
    put:
      tags:
        - Transactions Module
      summary: Update details of a transaction
      description: Update details of a transaction
      parameters:
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric id of the transaction
      requestBody:
        description: Updated transaction details
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: food
                notes:
                  type: string
                  example: notes
          application/xml:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: food
                notes:
                  type: string
                  example: notes
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: food
                notes:
                  type: string
                  example: notes
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  transactionId:
                    type: integer
                    format: int64
                    example: 1000
                  createdAt:
                    type: string
                    example: '2022-09-04'
                  updatedAt:
                    type: string
                    example: '2022-09-04'
                  type:
                    type: string
                    example: electronic
                  category:
                    type: string
                    example: food
                  notes:
                    type: string
                    example: notes
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  transactionId:
                    type: integer
                    format: int64
                    example: 1000
                  createdAt:
                    type: string
                    example: '2022-09-04'
                  updatedAt:
                    type: string
                    example: '2022-09-04'
                  type:
                    type: string
                    example: electronic
                  category:
                    type: string
                    example: food
                  notes:
                    type: string
                    example: notes
        '405':
          description: Invalid input
      security:
        - Bearer: []
    patch:
      tags:
        - Transactions Module
      summary: Archive a transaction
      description: Archive a transaction
      parameters:
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric id of the transaction
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid transaction id
      security:
        - Bearer: []
components:
  schemas:
    Page:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
          example: 1
        startRange:
          type: string
          example: '2022-09-04'
        endRange:
          type: string
          example: '2022-10-04'
    Transactions:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 100000
          date:
            type: string
            example: '2022-09-01'
          description:
            type: string
            example: Golden Sun Bakery
          amount:
            type: number
            format: float
            example: 5
          currency:
            type: string
            example: EUR
          balance:
            type: number
            format: float
            example: 2082.79
    Transaction:
      type: object
      properties:
        date:
          type: string
          example: '2022-09-01'
        description:
          type: string
          example: Golden Sun Bakery
        amount:
          type: number
          format: float
          example: 5
        currency:
          type: string
          example: EUR
    TransactionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        date:
          type: string
          example: '2022-09-01'
        description:
          type: string
          example: Golden Sun Bakery
        amount:
          type: number
          format: float
          example: 5
        currency:
          type: string
          example: EUR
        balance:
          type: number
          format: float
          example: 2082.79
    TransactionDetail:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        transactionId:
          type: integer
          format: int64
          example: 1000
        createdAt:
          type: string
          example: '2022-09-04'
        updatedAt:
          type: string
          example: '2022-09-04'
        type:
          type: string
          example: electronic
        category:
          type: string
          example: food
        notes:
          type: string
          example: notes
    TransactionUpdate:
      type: object
      properties:
        category:
          type: string
          example: food
        notes:
          type: string
          example: notes
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
